### ISSUE TITLE
E2E tests - Parallel Run and Improve test Isolation

### ISSUE THREAD

**Issue by jpnovais** [Consensys/linea-monorepo#133]
## Description
End2End tests shall refactored to:
- allow them to run in parallel and 
- have better isolation

### Refactor Suggestions
One pinpoint at the moment is that we need to configure loads of environment variables in multiple files and know them by heart. This does not scale well and is error-prone. 

Alternatively, we can he a global setup helper(s) for the test setup, that is responsible:
 - provide the overall configs: l1-endpoint, l2-endpoint, smart contract address etc
 - create l1/l2 accounts on the fly and fund them from whale accounts in the genesis

## Motivation
- Simulate Real-World Scenarios: e.g Coordinator & Message anchoring will benefit from being restarted when other things are happening. This is like in production
- Speed up CI times
- Shift-Left - Faster feedback loop - by reducing e2e times developers are more likely to run them locally.

## Acceptance criteria
- [ ] All the tests suites run in parallel, including the coordinator-restart

**Comment by Filter94** [comment]
I think there are a few things to improve still:
* NodeJs installation alone takes 24 seconds which becomes a considerable share of total E2E time. Can we speed it up with cache?
* Env spin up takes 1m 30 seconds. I suspect most of the time is taken by contracts deployments. I know we had some effort in the past to speed deployments up, but I'd just like to revisit this, if we make it in an optimal way
* E2E testsuite itself takes 2 minutes, longest of which is `src/submission-finalization.spec.ts (106.366 s)`. We should see if there is a way to reduce the latency between L2 transaction sending to L1 finalization. As a compromise, we should consider using `latest` tag instead of `finalize`. Another thing we should revisist is Coordinator configuration. Some polling intervals and delays might be slowing us down.


@jonesho I think it would be good for you to take a look at that as you're proficient in the stack as a whole, as well as the typescript part of the E2E tests
